/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package seproject;

public class App {

    public static void main(String[] args) {
        // create [interface] ConfigStore = JsonConfigStore() [implements ConfigStore]
        // create ConfigService(ConfigStore)
        
        // create Controller with ConfigService
        System.out.println("Restaurant project");
    }
}
